######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 3 09:42:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . inc src
INCLUDEPATH += . inc /home/vl/symbian-sdks/s60_50/epoc32/include

# Input
HEADERS += inc/logger1.h \
    inc/callback.h
SOURCES += src/main.cpp \
    src/callback.cpp

OTHER_FILES += \
    group/TrackDelete.mmp
