#! /bin/bash

#################

    ##### S60 3rd
    #echo "Начало сборки для S60 3rd"	
	sdk="s60_30mr" #edit this to your sdk
	PLATFORM="gcce"
	TARGET="urel"
			

###s60 3rd ed config
unsignedsisname="DiskActive.sis"
unsignedsisname2="DickActiveConf.sis"
signedsisname="app.sisx"
pkgfile3rdEd="pro.pkg"
pkg2="DiskActive.pkg"
cerfile="<path to your cer>"
keyfile="<path to your key>"
signingpassword="0000"
###

############## END: Build Config

export PATH=/home/vl/gnupoc:${PATH}
export EPOCROOT=/home/vl/symbian-sdks/s60_30mr/
export PLATFORM=${PLATFORM}
export TARGET=${TARGET}

START_TIME=`date +%s`

case $1 in
all)
    echo "Начало сборки"
   # echo "Очистка"
   # abld clean ${PLATFORM} ${TARGET}
    #bldmake clean
    #echo "Очистка заершена, сборка"
	bldmake bldfiles
	abld build ${PLATFORM} ${TARGET}
	echo "Конец сборки"
	
	echo "makesis"
	
		##### S60 3rd
		rm $unsignedsisname
		makesis $pkgfile3rdEd $unsignedsisname
		makesis $pkg2 $unsignedsisname2
		###########
	
	echo "Конец makesis"	   	

END_TIME=`date +%s`
ELAPSED=`expr $END_TIME - $START_TIME`
echo ""
echo "Сборка закончена - потрачено времени: " `date -d 00:00:$ELAPSED +%H:%M:%S`
;;

clean)
echo "//BEGIN clean//////////////////////"
abld clean $PLATFORM $TARGET
bldmake clean
echo "//END clean//////////////////////"

END_TIME=`date +%s`
ELAPSED=`expr $END_TIME - $START_TIME`
echo ""
echo "Clean finished - Elapsed time: " `date -d 00:00:$ELAPSED +%H:%M:%S`
;;

*)
   echo "invalid command param: just all or clean"
;;
esac
